config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :messages
  root "messages#index"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    # For using MySQL on Sinatra, two ways:
    # 1)
    # client = Mysql2::Client.new(:host => "localhost", :username => "root", :database => "DevBBQ_development")
    # @messages = client.query("SELECT * FROM messages WHERE user_id = #{current_user.id}")
    # 2)
    # @messages = ActiveRecord::Base.connection.select_all("SELECT * FROM messages WHERE user_id = #{current_user.id}").rows
    
    # Rails way, as usual like SQLite/PG:
    @messages = Message.where(user_id: current_user.id)
    @message = current_user.messages.build
  end

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save!
        MessageMailer.devbbq_email(@message.title, @message.content).deliver_now
        flash[:notice] = "You have successfully sent an email to DevBBQ!"
      end
      format.html
      format.js
    end   
  end

  private
  def message_params
    params.require(:message).permit(:title, :content, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    MessageMailer.welcome_email(resource).deliver_now unless resource.invalid?
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    resource.messages.each do |m|
      m.destroy
    end
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevBBQTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/messages/_dashboard.html.erb
<% if current_user.admin == true %>
  <%= link_to "Go to Admin Panel", rails_admin_path %>
<% end %>

app/views/messages/_flash.html.erb
<% flash.each do |name, msg| -%>
  <% if name == 'notice' %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert alert-success" %>
  <% elsif name == 'alert' %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert alert-danger" %>
  <% end %>
<% end %>

app/views/messages/_header.html.erb
<nav class="navbar navbar-default">
  <ul class="nav nav-pills">
    <li role="presentation" class="left" id="big-banner"><h2>EmailSender</h2></li>
    <li role="presentation" class="left" id="small-banner"><h4>EmailSender</h4></li>

    <% if current_user %>
      <li role="presentation" class="right" id="text">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      </li>
      <li role="presentation" class="right" id="icon">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
        <% end %>
      </li>

      <li role="presentation" class="right" id="text">
        <%= link_to "Edit Account", edit_user_registration_path %>
      </li>
      <li role="presentation" class="right" id="icon">
        <%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <% end %>
      </li>

      <li role="presentation" class="right" id="text">
        <%= link_to "Home", messages_path %>
      </li>
      <li role="presentation" class="right" id="icon">
        <%= link_to messages_path do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
        <% end %>
      </li>

      <% if current_user.admin == true %>
        <li role="presentation" class="right" id="text">
          <%= link_to "Go to Admin Panel", rails_admin_path %>
        </li>
        <li role="presentation" class="right" id="icon">
          <%= link_to rails_admin_path do %>
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          <% end %>
        </li>
      <% end %>

    <% else %>
      <li role="presentation" class="right" id="text">
        <%= link_to "Log In", new_user_session_path %>
      </li>
      <li role="presentation" class="right" id="icon">
        <%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>



        

app/views/messages/_message.html.erb
<div class="message">
  <h4>Subject: <%= message[:title] %></h4>
  <p>Body: <%= message[:content] %></p>
</div>

app/views/messages/_new_message.html.erb
<%= form_for @message, remote: true, id: 'new_message' do |f| %>
  <%if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved: </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group" id="lg-margin">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", placeholder: "Content" %>
  </div>
  <div class="submit">
    <%= f.submit "Send Message"%>
  </div>
<% end %>

app/views/messages/create.js.erb
$('#messages').append('<%= j render(@message) %>');

$("#new_message")[0].reset();

$('.flash-messages').html("<%= j (content_tag :div, flash[:notice], :id => 'flash_#{name}', :class => 'alert alert-success') %>");

app/views/messages/index.html.erb
<div class="header">
  <%= render "header" %>
</div>

<div class="flash-messages">
  <%= render "flash" %>
</div> 

<div id="new-message-banner">
  <h3>Send A Message To DevBBQ</h3>
</div>

<div id="new-message">
  <%= render "new_message" %>
</div>

<div id="chart">
  <%# column_chart Message.group_by_hour_of_day(:created_at, format: "%l %P").count %>
  <%# column_chart Message.group_by_day(:created_at).count %>
  <%= column_chart Message.where(user_id: current_user.id).group_by_period(:day, :created_at).count %>
</div>

<div id="switch-btn-wrap">
  <button id="switch-btn">View/Hide All Messages Sent</button>
</div>

<div id="messages">
  <%= render @messages %>
</div>